def some(x):
    return x/0 # заложим ошибку в функцию some

print(some(7))
